name: PR Checks
on:
  push:
    branches:
      - main
      - issue-653
  pull_request:
jobs:
  'Checking':
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: '        Startup ChromeDriver and Display in Ubuntu'
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: |
          export DISPLAY=:99.0
          sh -e /etc/init.d/xvfb start
          sleep 3 # give xvfb some time to start
      - name: '        Tests'
        shell: bash
        env:
          DISPLAY: ':99'
        run: |
          npm ci
          npm run test:jest
      - name: '        Tests - Mocha'
        run: npm run test:mocha
        shell: bash
      - name: '        Create COV_REPORT'
        run: |
          mkdir COV_REPORT
      - name: '        Copy jest results'
        run: |
          cp coverage_jest/coverage-final.json COV_REPORT/coverage-final-jest.json
      - name: '        Copy mocha results'
        run: |
            cp coverage/coverage-final.json COV_REPORT/coverage-final-mocha.json
